Module 1 capstone project
lengushuru/first_capstone pull request #1
Opened 2022-12-03 20:16 UTC by lengushuru

**Project description**

- personalized content on the page
- Build two pages: The home page and the About page
- website responsive for mobile and desktop.
-nav menu with links
-implemented mobile menu
- web deployed with GitHub pages
- Featured speaker section created dynamically
- recorded presentation video

2022-12-03 21:11 UTC, Abenezer-Tilahun requested changes
Hi @lengushuru   , 

Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻
✔️ No Linters error
✔️ You used correct GitHub Flow.
✔️ Professional README 
✔️ Good commit messages

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️

_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 21:11 UTC, Abenezer-Tilahun commented on about.html
> +  </section>
- [ ] As stated the project requirement The pages should look almost identical to the original design. Small adjustments like text or image changes are acceptable. So Between the "Home" section and "Past event" section you just missed one section from the design guidelines "Logo" section, So kindly check and fix it.

Your About page Look likes this : 

![Capture](https://user-images.githubusercontent.com/93598189/205461955-4b8126f6-67e5-4f66-bcb6-9bb9a13e3859.PNG)

The Design Guidelines About Page Look likes this : 

![Capture](https://user-images.githubusercontent.com/93598189/205461979-c95f5555-6b15-4463-bdfd-b722e716048f.PNG)

2022-12-03 21:11 UTC, Abenezer-Tilahun commented on about.html
> +  </footer>
- [ ]  As stated the project requirement The pages should look almost identical to the original design. Small adjustments like text or image changes are acceptable. So on the desktop version there is no "Partner" section Just like the design Guidelines and adjust the background color of footer section just like the design : So Kindly Fix it.

The design Guidelines About page Look likes this : 

![Capture](https://user-images.githubusercontent.com/93598189/205462072-2080a4f5-be79-480b-aa38-6c673260174d.PNG)

Your Project About Page Look this : 

![Capture](https://user-images.githubusercontent.com/93598189/205462123-9646cb0e-3f05-41f7-af55-8dcf88e44359.PNG)

2022-12-03 21:11 UTC, Abenezer-Tilahun commented on index.html
> +        <h2>SAM<span class="logo">BURU</span></h2>
- [ ] As stated the project requirement for interaction for links  I recommend you to make The logo in the header links to the home page.

![Capture](https://user-images.githubusercontent.com/93598189/205462220-031e01e1-f1c4-41e5-9041-396a49d5c654.PNG)

2022-12-03 22:46 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @lengushuru 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️

## Required Changes:
_Kindly check the comments below_


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 22:46 UTC, ha-manel commented on index.html
> +    <h1 class="page-title"> SAMBURU UNIVERSITY TECHNOLOGY<br> WEEK</h1>
- [ ] As requested by the previous reviewer, kindly make the first header an `h1` tag and the second one `h2` 👍

2022-12-03 22:46 UTC, ha-manel commented on README.md
>  ## 🙏 Acknowledgments <a name="acknowledgements"></a>
- [ ] As requested by the previous reviewer, kindly add a line here that gives credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-12-03 22:46 UTC, ha-manel commented on about.html
> +  </section>
- [ ] As mentioned by the previous reviewer, in the about page, the partners section is hidden in desktop view, but shown in mobile, and the footer is dark in desktop view but it's light colored in mobile view, kindly make the necessary changes to satisfy this description 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/205465022-0b8ecd08-b9f4-4303-ba61-9b9bdae0b5a3.png)
![image](https://user-images.githubusercontent.com/50721479/205465041-5ec5ce2c-5143-4ea9-a2fb-82ab0e767f1b.png)

## Guidelines:
![image](https://user-images.githubusercontent.com/50721479/205465030-0f8f53a4-77b5-42e0-81b5-1f09f95099fa.png)
![image](https://user-images.githubusercontent.com/50721479/205465050-7212826d-c03c-43c1-9199-aa281e26c654.png)

2022-12-03 23:16 UTC, Bondok6 requested changes
## Hi @lengushuru 🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

 ## Required Changes ♻️
- [ ] _Check the comments under the review._ ⬇

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 23:16 UTC, Bondok6 commented on README.md
>  ## 🙏 Acknowledgments <a name="acknowledgements"></a>
- [ ] Your README is well documented 💯 But As the previous reviewers mentioned and according to the requirements, Kindly give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

> Requirement ⬇
![image](https://user-images.githubusercontent.com/45231276/205465782-c357cd1d-4c15-48fa-8544-36cccfdc84a9.png)

2022-12-03 23:16 UTC, Bondok6 commented on about.html
> +  </section>
- [ ] As the previous reviewers mentioned, and according to the original design. ⬇
- About page should contain only dark `Footer` section in `Desktop version`, so kindly hide the partner section on desktop version and add dark footer section.
- About page should contain both the `Partner` section and white `Footer` section in `Mobile version`, so Kindly add white footer section in mobile version.

2022-12-05 14:56 UTC, lengushuru commented
required changes on the READMe file were already in the master README

2022-12-05 17:43 UTC, bimbolabuari reviewed
Hello @lengushuru  👋,

_This is an additional review due to the second opinion request._

- Kudos for working on your first capstone project ✊  
   - However, the previous CR was right about the two requested changes 
        - In the project requirement, we are asked to give **appropriate** credit to the author 
           which is required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/), Kindly add this to the 
            acknowledgement section of your README file explicitly stating [Cindy Shin in 
            Behance](https://www.behance.net/adagio07) the design author.
   

        - It is required that we follow the design guidelines, including colours, typography and layout (composition and space between elements).
       
<img width="1031" alt="Screenshot 2022-12-05 at 18 33 35" src="https://user-images.githubusercontent.com/66112760/205705469-444ca349-9725-490d-af35-d969c8769ceb.png">
<img width="994" alt="Screenshot 2022-12-05 at 18 42 13" src="https://user-images.githubusercontent.com/66112760/205705605-705c6afb-69b1-4c08-b4c4-37961a70a410.png">


Keep rocking 🚀!

2023-01-02 06:39 UTC, merged